name: Test and Deploy Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_python_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: |
          python -m unittest test_Calculator.py

  deploy:
    runs-on: ubuntu-latest
    needs: test_python_code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Deploy Application
        run: |
          echo "🚀 Deploying application..."
          python calculator.py
          
